name: Automatic Rebase 
on:
  push:
    branches:
      - "main"
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: ${{ github.job.status }} == "success"
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Git config
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Rebase main
        run: |
          git checkout staging
          git rebase main
      - name: Force push
        run: |
          git add .
          git push -f origin staging
