name: Automatic Rebase
on:
  push:
    branches: [ main ]

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
      - name: Git fetch
        run: |
          git checkout main
          git fetch -all
          git checkout staging
          git rebase origin/main
          git push -f origin staging
