name: Automatic Rebase
on:
  push:
    branches: [ main ]

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
      - name: Set up config
        run: |
          git config user.name hankpkj
          git config user.email hankpkj@gmail.com
      - name: Git fetch
        run: git fetch
      - name: Git checkout staging
        run: git checkout origin/staging
      - name: Git reabse
        run: git rebase origin/main
      - name: Git push
        run: |
          git add .
          git commit -m "complete rebase"
          git push -f origin staging
