name: Automatic Rebase
on: 
  push:
    branches:
      - "main"
jobs:

  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: checkout staging
        run: git checkout staging
      - name: rebase main
        run: git rebase main
      - name: push
        run: |
          git add .
          git commit -m "rebase main"
          git push -f origin staging
