name: Automatic Rebase
on:
  push: 
    branches:
      - "main"
jobs:

  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    # if: github.repository == 'staging'
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branches: "staging"
