name: Automatic Rebase 
on:
  push:
    branches:
      - "main"
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Git config
        env:
          NAME: ${GITHUB_ACTOR}
          EMAIL: ${{ github.event.head_commit.author.email }}
        run: |
          git config --global user.email $EMAIL
          git config --global user.name $NAME
      - name: Rebase main
        run: |
          git checkout staging
          git rebase main
      - name: Force push
        run: |
          git push -f origin staging
